spring:
  application:
    name: direction

  datasource:
    url: jdbc:mysql://localhost:3306/<db>
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: <username>
    password: <password>



